//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ruanmou.SOA.UnitTestProject.MyWebServiceTest {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MyWebServiceTest.MyWebServiceSoap")]
    public interface MyWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorldWithAuth", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorldWithAuth(string name_password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorldWithAuth", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldWithAuthAsync(string name_password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetName(int i);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetName", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetNameAsync(int i);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Plus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Plus(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Plus", ReplyAction="*")]
        System.Threading.Tasks.Task<int> PlusAsync(int x, int y);
        
        // CODEGEN: 消息 GetInfoRequest 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Ruanmou.SOA.UnitTestProject.MyWebServiceTest.GetInfoResponse GetInfo(Ruanmou.SOA.UnitTestProject.MyWebServiceTest.GetInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<Ruanmou.SOA.UnitTestProject.MyWebServiceTest.GetInfoResponse> GetInfoAsync(Ruanmou.SOA.UnitTestProject.MyWebServiceTest.GetInfoRequest request);
        
        // CODEGEN: 消息 GetUserRequest 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Ruanmou.SOA.UnitTestProject.MyWebServiceTest.GetUserResponse GetUser(Ruanmou.SOA.UnitTestProject.MyWebServiceTest.GetUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUser", ReplyAction="*")]
        System.Threading.Tasks.Task<Ruanmou.SOA.UnitTestProject.MyWebServiceTest.GetUserResponse> GetUserAsync(Ruanmou.SOA.UnitTestProject.MyWebServiceTest.GetUserRequest request);
        
        // CODEGEN: 消息 GetUserListRequest 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Ruanmou.SOA.UnitTestProject.MyWebServiceTest.GetUserListResponse GetUserList(Ruanmou.SOA.UnitTestProject.MyWebServiceTest.GetUserListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserList", ReplyAction="*")]
        System.Threading.Tasks.Task<Ruanmou.SOA.UnitTestProject.MyWebServiceTest.GetUserListResponse> GetUserListAsync(Ruanmou.SOA.UnitTestProject.MyWebServiceTest.GetUserListRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CustomSoapHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userNameField;
        
        private string passWordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string PassWord {
            get {
                return this.passWordField;
            }
            set {
                this.passWordField = value;
                this.RaisePropertyChanged("PassWord");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UserInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string nameField;
        
        private int ageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Age {
            get {
                return this.ageField;
            }
            set {
                this.ageField = value;
                this.RaisePropertyChanged("Age");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetInfo", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetInfoRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Ruanmou.SOA.UnitTestProject.MyWebServiceTest.CustomSoapHeader CustomSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string name;
        
        public GetInfoRequest() {
        }
        
        public GetInfoRequest(Ruanmou.SOA.UnitTestProject.MyWebServiceTest.CustomSoapHeader CustomSoapHeader, int id, string name) {
            this.CustomSoapHeader = CustomSoapHeader;
            this.id = id;
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetInfoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetInfoResult;
        
        public GetInfoResponse() {
        }
        
        public GetInfoResponse(string GetInfoResult) {
            this.GetInfoResult = GetInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUser", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetUserRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Ruanmou.SOA.UnitTestProject.MyWebServiceTest.CustomSoapHeader CustomSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int id;
        
        public GetUserRequest() {
        }
        
        public GetUserRequest(Ruanmou.SOA.UnitTestProject.MyWebServiceTest.CustomSoapHeader CustomSoapHeader, int id) {
            this.CustomSoapHeader = CustomSoapHeader;
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUserResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Ruanmou.SOA.UnitTestProject.MyWebServiceTest.UserInfo GetUserResult;
        
        public GetUserResponse() {
        }
        
        public GetUserResponse(Ruanmou.SOA.UnitTestProject.MyWebServiceTest.UserInfo GetUserResult) {
            this.GetUserResult = GetUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUserList", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetUserListRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Ruanmou.SOA.UnitTestProject.MyWebServiceTest.CustomSoapHeader CustomSoapHeader;
        
        public GetUserListRequest() {
        }
        
        public GetUserListRequest(Ruanmou.SOA.UnitTestProject.MyWebServiceTest.CustomSoapHeader CustomSoapHeader) {
            this.CustomSoapHeader = CustomSoapHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUserListResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetUserListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Ruanmou.SOA.UnitTestProject.MyWebServiceTest.UserInfo[] GetUserListResult;
        
        public GetUserListResponse() {
        }
        
        public GetUserListResponse(Ruanmou.SOA.UnitTestProject.MyWebServiceTest.UserInfo[] GetUserListResult) {
            this.GetUserListResult = GetUserListResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MyWebServiceSoapChannel : Ruanmou.SOA.UnitTestProject.MyWebServiceTest.MyWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyWebServiceSoapClient : System.ServiceModel.ClientBase<Ruanmou.SOA.UnitTestProject.MyWebServiceTest.MyWebServiceSoap>, Ruanmou.SOA.UnitTestProject.MyWebServiceTest.MyWebServiceSoap {
        
        public MyWebServiceSoapClient() {
        }
        
        public MyWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        public string HelloWorldWithAuth(string name_password) {
            return base.Channel.HelloWorldWithAuth(name_password);
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldWithAuthAsync(string name_password) {
            return base.Channel.HelloWorldWithAuthAsync(name_password);
        }
        
        public string GetName(int i) {
            return base.Channel.GetName(i);
        }
        
        public System.Threading.Tasks.Task<string> GetNameAsync(int i) {
            return base.Channel.GetNameAsync(i);
        }
        
        public int Plus(int x, int y) {
            return base.Channel.Plus(x, y);
        }
        
        public System.Threading.Tasks.Task<int> PlusAsync(int x, int y) {
            return base.Channel.PlusAsync(x, y);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ruanmou.SOA.UnitTestProject.MyWebServiceTest.GetInfoResponse Ruanmou.SOA.UnitTestProject.MyWebServiceTest.MyWebServiceSoap.GetInfo(Ruanmou.SOA.UnitTestProject.MyWebServiceTest.GetInfoRequest request) {
            return base.Channel.GetInfo(request);
        }
        
        public string GetInfo(Ruanmou.SOA.UnitTestProject.MyWebServiceTest.CustomSoapHeader CustomSoapHeader, int id, string name) {
            Ruanmou.SOA.UnitTestProject.MyWebServiceTest.GetInfoRequest inValue = new Ruanmou.SOA.UnitTestProject.MyWebServiceTest.GetInfoRequest();
            inValue.CustomSoapHeader = CustomSoapHeader;
            inValue.id = id;
            inValue.name = name;
            Ruanmou.SOA.UnitTestProject.MyWebServiceTest.GetInfoResponse retVal = ((Ruanmou.SOA.UnitTestProject.MyWebServiceTest.MyWebServiceSoap)(this)).GetInfo(inValue);
            return retVal.GetInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ruanmou.SOA.UnitTestProject.MyWebServiceTest.GetInfoResponse> Ruanmou.SOA.UnitTestProject.MyWebServiceTest.MyWebServiceSoap.GetInfoAsync(Ruanmou.SOA.UnitTestProject.MyWebServiceTest.GetInfoRequest request) {
            return base.Channel.GetInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ruanmou.SOA.UnitTestProject.MyWebServiceTest.GetInfoResponse> GetInfoAsync(Ruanmou.SOA.UnitTestProject.MyWebServiceTest.CustomSoapHeader CustomSoapHeader, int id, string name) {
            Ruanmou.SOA.UnitTestProject.MyWebServiceTest.GetInfoRequest inValue = new Ruanmou.SOA.UnitTestProject.MyWebServiceTest.GetInfoRequest();
            inValue.CustomSoapHeader = CustomSoapHeader;
            inValue.id = id;
            inValue.name = name;
            return ((Ruanmou.SOA.UnitTestProject.MyWebServiceTest.MyWebServiceSoap)(this)).GetInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ruanmou.SOA.UnitTestProject.MyWebServiceTest.GetUserResponse Ruanmou.SOA.UnitTestProject.MyWebServiceTest.MyWebServiceSoap.GetUser(Ruanmou.SOA.UnitTestProject.MyWebServiceTest.GetUserRequest request) {
            return base.Channel.GetUser(request);
        }
        
        public Ruanmou.SOA.UnitTestProject.MyWebServiceTest.UserInfo GetUser(Ruanmou.SOA.UnitTestProject.MyWebServiceTest.CustomSoapHeader CustomSoapHeader, int id) {
            Ruanmou.SOA.UnitTestProject.MyWebServiceTest.GetUserRequest inValue = new Ruanmou.SOA.UnitTestProject.MyWebServiceTest.GetUserRequest();
            inValue.CustomSoapHeader = CustomSoapHeader;
            inValue.id = id;
            Ruanmou.SOA.UnitTestProject.MyWebServiceTest.GetUserResponse retVal = ((Ruanmou.SOA.UnitTestProject.MyWebServiceTest.MyWebServiceSoap)(this)).GetUser(inValue);
            return retVal.GetUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ruanmou.SOA.UnitTestProject.MyWebServiceTest.GetUserResponse> Ruanmou.SOA.UnitTestProject.MyWebServiceTest.MyWebServiceSoap.GetUserAsync(Ruanmou.SOA.UnitTestProject.MyWebServiceTest.GetUserRequest request) {
            return base.Channel.GetUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ruanmou.SOA.UnitTestProject.MyWebServiceTest.GetUserResponse> GetUserAsync(Ruanmou.SOA.UnitTestProject.MyWebServiceTest.CustomSoapHeader CustomSoapHeader, int id) {
            Ruanmou.SOA.UnitTestProject.MyWebServiceTest.GetUserRequest inValue = new Ruanmou.SOA.UnitTestProject.MyWebServiceTest.GetUserRequest();
            inValue.CustomSoapHeader = CustomSoapHeader;
            inValue.id = id;
            return ((Ruanmou.SOA.UnitTestProject.MyWebServiceTest.MyWebServiceSoap)(this)).GetUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ruanmou.SOA.UnitTestProject.MyWebServiceTest.GetUserListResponse Ruanmou.SOA.UnitTestProject.MyWebServiceTest.MyWebServiceSoap.GetUserList(Ruanmou.SOA.UnitTestProject.MyWebServiceTest.GetUserListRequest request) {
            return base.Channel.GetUserList(request);
        }
        
        public Ruanmou.SOA.UnitTestProject.MyWebServiceTest.UserInfo[] GetUserList(Ruanmou.SOA.UnitTestProject.MyWebServiceTest.CustomSoapHeader CustomSoapHeader) {
            Ruanmou.SOA.UnitTestProject.MyWebServiceTest.GetUserListRequest inValue = new Ruanmou.SOA.UnitTestProject.MyWebServiceTest.GetUserListRequest();
            inValue.CustomSoapHeader = CustomSoapHeader;
            Ruanmou.SOA.UnitTestProject.MyWebServiceTest.GetUserListResponse retVal = ((Ruanmou.SOA.UnitTestProject.MyWebServiceTest.MyWebServiceSoap)(this)).GetUserList(inValue);
            return retVal.GetUserListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ruanmou.SOA.UnitTestProject.MyWebServiceTest.GetUserListResponse> Ruanmou.SOA.UnitTestProject.MyWebServiceTest.MyWebServiceSoap.GetUserListAsync(Ruanmou.SOA.UnitTestProject.MyWebServiceTest.GetUserListRequest request) {
            return base.Channel.GetUserListAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ruanmou.SOA.UnitTestProject.MyWebServiceTest.GetUserListResponse> GetUserListAsync(Ruanmou.SOA.UnitTestProject.MyWebServiceTest.CustomSoapHeader CustomSoapHeader) {
            Ruanmou.SOA.UnitTestProject.MyWebServiceTest.GetUserListRequest inValue = new Ruanmou.SOA.UnitTestProject.MyWebServiceTest.GetUserListRequest();
            inValue.CustomSoapHeader = CustomSoapHeader;
            return ((Ruanmou.SOA.UnitTestProject.MyWebServiceTest.MyWebServiceSoap)(this)).GetUserListAsync(inValue);
        }
    }
}
